version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: ${APP_NAME}-nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/default.conf:/tmp/default.template
      - ./src:/var/www/html:rw,cached
      - ./certs:/etc/certs
    depends_on:
      - web
    restart: always
    entrypoint: /bin/bash -c 'cat /tmp/default.template | sed "s/\\\$$domain/${DOMAIN}/g" > /etc/nginx/conf.d/default.conf && nginx -g "daemon off;"'
    networks:
      - demoserver

  db:
    image: rethinkdb:latest
    container_name: ${APP_NAME}-rethinkdb
    ports:
      - 8080:8080
    command: ['rethinkdb', '--initial-password', '7db2ca0e-760f-4dcb-8d69-639ec18cdb0f', '--bind', 'all']
    restart: always
    networks:
      - demoserver

  web:
    image: webapp-flask
    container_name: ${APP_NAME}-flask
    build:
      context: .
      dockerfile: Dockerfile-flask
    volumes:
      - './server:/server'
    ports:
      - 8000:8000
    command: ['python', 'server.py']
    environment:
      - DB_HOST=db
      - DB_PORT=28015
      - DB_USER=admin
      - DB_PASS=${DB_PASS}
    restart: always
    depends_on:
      - db
    networks:
      - demoserver

networks:
  demoserver:
    driver: bridge